fixtures:
  symlinks:
    pixelated: "#{source_dir}"
  repositories:
    apt: "https://leap.se/git/puppet_apt"
    lsb: "https://leap.se/git/puppet_lsb"
    common: "https://leap.se/git/puppet_common"
    rsyslog: "https://leap.se/git/puppet_rsyslog"
    shorewall: "https://leap.se/git/puppet_shorewall"
    concat: "https://leap.se/git/puppet_concat"
